[platformio]
default_envs = sensor_pcb_v3

[env]
extra_scripts = pre:scripts/patch_bsec2.py
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BME280 Library @ 2.3.0
    https://github.com/boschsensortec/Bosch-BME68x-Library.git#4f37df69dde205e4f58d2bb9a45568c61e128e86
    https://github.com/boschsensortec/Bosch-BSEC2-Library.git#4f559a6aa450f0ce436e602b42dc384f52128c66
    lil-sensor-protocol=symlink://../shared
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
    -Wall
    -Wextra
    -Wno-unused-parameter
build_unflags = -std=gnu++11
board_build.partitions = min_spiffs.csv

[env:sensor_pcb_v3]
build_flags =
    ${env.build_flags}
    -DPCB_VERSION=3

[env:sensor_pcb_v4]
build_flags =
    ${env.build_flags}
    -DPCB_VERSION=4
